language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
  cache:
    directories:
      - $HOME/.gradle
script: ./gradlew clean publishPlugins
after_success:
  if [ "${TRAVIS_BRANCH}" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    ./gradlew publishPlugins -Pgradle.publish.key="${publishKey}" -Pgradle.publish.secret="${publishSecret}"
  fi